### ISSUE TITLE
Missing reset/cleanup in provided example (README.md) leading to terminal state corruption

### ISSUE THREAD

**Issue by glenux** [crystallabs/tput.cr#3]
### Context

I'm experiencing an issue with the example provided in the tput.cr library's `README.md` (rather than the tput.cr library itself)... and as a result, I don't know what the good practices are for using tput.cr :sweat: 

I've searched the source code and tried various things before the exit (soft_reset, clear, etc.), but I haven't (yet) found a function that solves the problem.

### Environment

- **Crystal Version:** 1.10.1
- **tput.cr Version:** v1.0.7
- **Operating System:** Debian Bookworm (12)
- **Terminal Emulator:** Konsole 23.08.1 , xterm 386-1, qterminal 1.3.0-1, 

### Reproduction Steps

1. Create a project using the `shards.yml` below :
```
---
name: Test
version: 0.1.0

targets:
  test:
    main: src/test.cr

dependencies:
  tput:
    github: crystallabs/tput.cr
    version: ~> 1.0

license: MIT
```
2. Copy-paste the example from tput.cr's `README.md` in `src/test.cr`.
3. Compile with `shards build` and executed in Konsole.

### Observed Behavior

* Post-execution, the terminal is left in an unusable state with no echo (invisible text), and the cursor is still colored.
* No specific error logs are generated by tput.cr or by the terminal.
* Typing "reset" in the terminal restores its functionality, indicating a probable issue in the cleanup sequence of the example code.

### Insights/Fixes

The example code in tput.cr's documentation likely lacks an adequate cleanup or reset sequence for the terminal state, leading to this issue.
